name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t siarhkul/docker-and-kubernetes -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true siarhkul/docker-and-kubernetes npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Display deployment package path
        run: echo $(pwd)/deploy.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4 
        with:
          name: deployment-package
          path: deploy.zip

